apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
    version: blue   # 👈 change to "green" when switching
  type: NodePort
  ports:
    - port: 80          # Service port
      targetPort: 3000  # Container port
      nodePort: 31000   # Fixed port for access (range: 30000–32767)
